# Create environment:
#   conda env create --file environment.yml
# Remove environment:
#   conda remove --name mechanoconf --all


name: mechanoconf

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - napari-plugin-engine
  - pyclesperanto-prototype
  - ocl_icd_wrapper_apple

  # Standard scientific Python
  - numpy
  - matplotlib
  - scipy
  - pandas

  - pip:

    # Code quality
    - pre-commit
    - "black[jupyter]"
    - isort
    - ruff

    # Plotting
    - seaborn

    # Jupyter
    - jupyterlab
    - notebook

    # ML and stats
    - scikit-learn

    # Imaging
    - aicsimageio
    - czifile
    - aicspylibczi>=3.0.5
    - scikit-image
    - napari-skimage-regionprops
    - napari-simpleitk-image-processing
    - napari-pyclesperanto-assistant
    - pyradiomics
    - napari-laptrack

    # Statistics
    - statannotations

    # Misc.
    - watermark
