# Create environment:
#   conda env create --file environment.yml
# Remove environment:
#   conda remove --name mechanoconf --all


name: mechanoconf

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip=24.0

  # Standard scientific Python
  - numpy=2.2.0
  - matplotlib=3.8.4
  - scipy=1.13.0
  - pandas=2.2.2

  - pip:

    # Code quality
    - pre-commit==3.7.0
    - black==24.3.0
    - isort==5.13.2
    - ruff==0.3.6

    # Plotting
    - seaborn==0.13.2

    # Jupyter
    - jupyterlab==4.1.6
    - notebook==7.1.2

    # ML and stats
    - scikit-learn==1.4.2

    # Imaging
    - scikit-image==0.23.1
    - aicsimageio==4.14.0
    - czifile==2019.7.2
    - aicspylibczi==3.2.1
    - napari==0.4.19
    - napari_skimage_regionprops>=0.9.0
    - napari-simpleitk-image-processing==0.4.9
    - napari-pyclesperanto-assistant==0.25.0
    - pyradiomics==3.0.1
    - napari-laptrack==0.2.0
    - pyqt5==5.15.11

    # Statistics
    - statannotations==0.7.1

    # Misc.
    - siphash24==1.7
